# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0003_auto_20170903_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_guid',
            field=models.CharField(default='adasdad5153a1ds5311ads33', max_length=250, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
