# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0005_producttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
