# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Ingredient')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Store')),
            ],
        ),
    ]
