# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
