# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0001_initial'),
        ('Inventory', '0004_auto_20170823_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Purchases.Purchase'),
        ),
    ]
