# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_auto_20170822_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=254, unique=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('last_activation', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.User')),
            ],
        ),
    ]
